# Generated by Django 5.2.8 on 2026-06-29 14:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activationtoken",
            name="unique_active_token",
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                max_length=2,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Буквенный код страны",
            ),
        ),
        migrations.AddConstraint(
            model_name="activationtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2026,
                            6,
                            29,
                            14,
                            5,
                            39,
                            379263,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                fields=("user",),
                name="unique_active_token",
            ),
        ),
    ]
