# Generated by Django 5.2.8 on 2026-07-11 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_activationtoken_unique_active_token_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activationtoken",
            name="unique_active_token",
        ),
        migrations.AddConstraint(
            model_name="activationtoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "expires_at__gt",
                        datetime.datetime(
                            2026,
                            7,
                            11,
                            10,
                            27,
                            57,
                            562528,
                            tzinfo=datetime.timezone.utc,
                        ),
                    )
                ),
                fields=("user",),
                name="unique_active_token",
            ),
        ),
    ]
