# Generated by Django 5.2.8 on 2026-05-07 11:42

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Название национальности",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        verbose_name="Буквенный код национальности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Национальность",
                "verbose_name_plural": "Национальности",
                "ordering": ("nationality",),
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=150,
                        validators=[
                            core.validators.KirillicLettersValidator()
                        ],
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        validators=[
                            core.validators.KirillicLettersValidator()
                        ],
                        verbose_name="Фамилия",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "nationality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authors.nationality",
                        verbose_name="Национальность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ("last_name", "first_name"),
            },
        ),
    ]
