# Generated by Django 5.2.8 on 2026-06-29 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationality",
            name="code",
            field=models.CharField(
                max_length=2,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Буквенный код национальности",
            ),
        ),
    ]
