# Generated by Django 5.2.8 on 2026-01-17 14:07

import django.core.validators
import isbn_field.fields
import isbn_field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, verbose_name="Автор"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BookInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Доступна"),
                            ("BUSY", "Занята"),
                            ("RESERVED", "Зарезервирована"),
                        ],
                        max_length=9,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перечень книг",
                "verbose_name_plural": "Перечни книг",
                "ordering": ("status",),
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Жанр"
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Книга"
                    ),
                ),
                (
                    "pages",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Количество страниц",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        db_index=True, verbose_name="Дата издания"
                    ),
                ),
                (
                    "isbn",
                    isbn_field.fields.ISBNField(
                        max_length=13,
                        unique=True,
                        validators=[isbn_field.validators.ISBNValidator],
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "age_rating",
                    models.CharField(
                        choices=[
                            ("ABOVE_ZERO", "0+"),
                            ("ABOVE_SIX", "6+"),
                            ("ABOVE_TWELVE", "12+"),
                            ("ABOVE_SIXTEEN", "16+"),
                            ("ABOVE_EIGHTEEN", "18+"),
                        ],
                        max_length=14,
                        verbose_name="Возрастной рейтинг",
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="authors", to="books.author"
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ("title",),
            },
        ),
    ]
