# Generated by Django 5.2.8 on 2026-05-07 11:42

import django.core.validators
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=150,
                        unique=True,
                        verbose_name="Жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Книга"
                    ),
                ),
                (
                    "pages",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Количество страниц",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(verbose_name="Дата издания"),
                ),
                (
                    "isbn",
                    isbn_field.fields.ISBNField(
                        max_length=13,
                        unique=True,
                        validators=[isbn_field.validators.ISBNValidator],
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "age_rating",
                    models.CharField(
                        choices=[
                            ("ABOVE_ZERO", "0+"),
                            ("ABOVE_SIX", "6+"),
                            ("ABOVE_TWELVE", "12+"),
                            ("ABOVE_SIXTEEN", "16+"),
                            ("ABOVE_EIGHTEEN", "18+"),
                        ],
                        max_length=14,
                        verbose_name="Возрастной рейтинг",
                    ),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="books",
                        to="authors.author",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="books",
                        to="books.genre",
                        verbose_name="Жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="BookInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Доступна"),
                            ("BUSY", "Занята"),
                            ("RESERVED", "Зарезервирована"),
                        ],
                        max_length=9,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="book_inventory",
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
                (
                    "curr_holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrowed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Перечень книг",
                "verbose_name_plural": "Перечни книг",
                "ordering": ("status",),
            },
        ),
    ]
