# Generated by Django 5.2.8 on 2026-06-29 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinventory",
            name="borrowed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи"
            ),
        ),
        migrations.AddField(
            model_name="bookinventory",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="bookinventory",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_inventory",
                to="books.book",
                verbose_name="Книга",
            ),
            preserve_default=False,
        ),
    ]
